version: "3.9"

services:
  web:
    container_name: restaurant_api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command:  bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"